<?php
/**
 * Sidebar menu for store
 */
?>
<?php 
	$layer = Mage::getSingleton('catalog/layer');
	$_category = $layer->getCurrentCategory();
	$currentCategoryId = $_category->getId();
?>
<?php if($currentCategoryId == 17): // "Catalog" ?>
<div class="container">
	<div class="container-top">Catalog</div>
	<div class="container-content">
		<div class="sidebar-menu">
	
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pronav_catalog_menu')->toHtml() ?>
		
		</div>
	</div>
</div>
<?php endif; ?> 