<?php
    $_productCollection = $this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $productsLimit = 4;
?>


<?php $_collectionSize = $_productCollection->count() ?>
<?php $_columnCount = $this->getColumnCount(); ?>
<ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
    <?php $i = 1; foreach ($_productCollection as $_product): ?>
    	<?php //$_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
        <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount == 0 || $i == $_collectionSize): ?> last<?php endif; ?>">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php $_imgSize = 465; ?>
                <?php if(Mage::getSingleton('cms/page')->getIdentifier() == 'home'  && Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms') : ?>
                	<?php $imageUrl = str_replace('index.php/', '', $this->getBaseUrl()) . 'media/catalog/product' . $_product->getSmallImage() ?>
                <?php else: ?>
                	<?php $imageUrl = $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>
				<?php endif; ?>
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                     src="<?php echo $imageUrl; ?>"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>
            <div class="product-info">
                <h2 class="product-name">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                    </a>
                </h2>
                <div class="price-cart">
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    
                    <div class="actions">
                    	<?php if (!$_product->getPriceOnDemand()): ?>
	                        <?php if($_product->isSaleable() && !$_product->canConfigure()): ?>
	                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
	                        <?php elseif($_product->isSaleable()): ?>
	                            <a title="<?php echo $this->__('View Details') ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
	                        <?php else: ?>
	                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
	                        <?php endif; ?>
                        <?php else: ?>
                        	<button type="button" title="<?php echo $this->__('Cere ofertă') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getBaseUrl() ?>contact/vanzari/?sku=<?php echo $_product->getSku(); ?>')"><span><span><?php echo $this->__('Cere ofertă') ?></span></span></button>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </li>
        <?php if ($i == $_columnCount) break; ?>
    <?php $i++; endforeach ?>
</ul>


