<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
	<?php echo $this->getChildHtml('header') ?>
    <div class="page">
        <div class="main-container col1-blank-layout">
            <div class="main">
                <?php echo $this->getChildHtml('breadcrumbs') ?>
                <div class="col-main">
                    <?php echo $this->getChildHtml('global_messages') ?>
                    <?php echo $this->getChildHtml('content') ?>
                    <?php echo $this->getLayout()->createBlock('interaktingslider/interaktingslider')->setBlockName('interaktingslider')->toHtml() ?> 
                    <?php if(Mage::getModel('cms/block')->load('m_home_center')->getIsActive() == true): ?>
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('m_home_center')->toHtml() ?> 
					<?php endif ?>
					<div class="about-box fleft">
					<?php if(Mage::getModel('cms/block')->load('m_home_about')->getIsActive() == true): ?>
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('m_home_about')->toHtml() ?> 
					<?php endif ?>
					</div>
					<div class="consumables-box fright">
					<?php echo $this->getLayout()->createBlock('catalog/product_list')->setCategoryId('2')->setTemplate('catalog/product/list-home-consumables.phtml')->toHtml() ?> 
					</div>
					<div class="fclear"></div>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
