<?php $_order = $this->getOrder(); ?>

<table cellspacing="0" cellpadding="0" border="0" width="100%" style="border:1px solid #bebcb7; background:#f8f7f5;">
	<thead>
		<tr>
			<th><span class="nobr">Produs</span></th>
			<th class="a-center"><span class="nobr">Cod</span></th>
			<th class="a-center">Cantitate</th>
			<th class="a-center">Subtotal</th>
		</tr>
	</thead>
	<?php $i=0; foreach ($_order->getAllItems() as $_item): ?>
	<?php if($_item->getParentItem()) continue; else $i++; ?>
	<tbody<?php echo $i%2 ? ' bgcolor="#eeeded"' : '' ?>>
		<?php echo $this->getItemHtml($_item) ?>
	</tbody>
	<?php endforeach; ?>
	<tfoot>
		<tr>
			<td colspan="4" align="left" style="padding:3px 9px">&nbsp;</td>
		</tr>
	</tfoot>
</table>