<div class="block block-banner">
        <?php if(strtolower(substr($this->getLinkUrl(),0,4))==='http' || strtolower(substr($this->getLinkUrl(),0,10))==='javascript' || strtolower(substr($this->getLinkUrl(),0,1))==='#'): ?>
            <a <?php echo $this->getLinkId() ? 'id="'.$this->getLinkId().'"' : '' ?> <?php echo $this->getLinkClass() ? 'class="'.$this->getLinkClass().'"' : '' ?> <?php echo $this->getLinkRel() ? 'rel="'.$this->getLinkRel().'"' : '' ?> href="<?php echo $this->getLinkUrl() ?>" title="<?php echo $this->__($this->getImgAlt()) ?>">
        <?php elseif($this->getLinkUrl()): ?>
            <a href="<?php echo $this->getUrl($this->getLinkUrl()) ?>" title="<?php echo $this->__($this->getImgAlt()) ?>">
        <?php endif; ?>
            <img src="<?php echo $this->getSkinUrl($this->getImgSrc()) ?>"<?php if(!$this->getLinkUrl()): ?> title="<?php echo $this->__($this->getImgAlt()) ?>"<?php endif; ?> alt="<?php echo $this->__($this->getImgAlt()) ?>" />
        <?php if($this->getLinkUrl()): ?>
        </a>
        <?php endif ?>
</div>
