<?php
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$selectedStateSegment = Mage::helper('pronav')->getSelectedStateSegment($currentUrl,  $this->getBaseUrl());
$selectedStateSegment = $selectedStateSegment ? $selectedStateSegment : 'index';

$baseUrl = Mage::getStoreConfig('web/seo/use_rewrites') ? $this->getBaseUrl() : $this->getBaseUrl() . 'index.php/';

if ($this->getNavConfig('pronav_status'))
{
   $output = '<ul id="pronav">';
   $navData = $this->getNavData();
   foreach ($navData as $data)
   {
      $urlKey = strlen($data['url_key']) > 0 && $data['url_key'] ? $data['url_key'] : '#';
      if ($data['static_block'] == 0 || ! $data['static_block'])
      {
         $output .= '<li id="' . $data['li_css_id'] . '" class="' . $data['li_css_class'] . '"><a href="' . $baseUrl . $urlKey . '" id="' . $data['css_id'] . '" class="' . $data['css_class'] . '">' . Mage::helper('pronav')->__($data['name']) . '</a></li>';
      } else {
         // item has static block
         $output .= '<li id="' . $data['li_css_id'] . '" class="' . $data['li_css_class'] . '"><a href="' . $baseUrl . $urlKey . '" id="' . $data['css_id'] . '" class="' . $data['css_class'] . '">' . Mage::helper('pronav')->__($data['name']) . '</a>';
         $output .= '<div class="sub">';
         $blockIdentifier = $this->getStaticBlockIdentifier($data['static_block']);
         $output .= $this->getLayout()->createBlock('cms/block')->setBlockId($blockIdentifier)->toHtml();
         $output .= '</div>';
         $output .= '</li>';
      }
   }
   ?>

<?php
   $output .= '<div style="clear:both;"></div>';
   echo $output;
}
?>
<div style="clear:both;"></div></ul>

<script>
jQuery(function() {
// add pronav selected state to body classes
jQuery('body').addClass('pronav-selected-<?php echo $selectedStateSegment ?>');
jQuery.fn.calcSubWidth = function() {
            rowWidth = 0;
            //Calculate row
            jQuery(this).find("ul.primary").each(function() { //for each ul...
                rowWidth += jQuery(this).width()+1; //Add each ul's width together
            });
        };
var paddingFix = 0;
function megaHoverOver(){
    jQuery(this).find(".sub").stop().fadeTo(<?php echo $this->getNavConfig('fadein')?>, 1, function(){
    			jQuery(this).css('filter','');
        }).show(); //Find sub and fade it in
     subPaddingLeft = jQuery(this).find('.sub').css('padding-right');
	 subPaddingRight = jQuery(this).find('.sub').css('padding-left');
	 if (subPaddingLeft && subPaddingRight)
	 {
		 subPaddingLeft = parseInt(subPaddingRight.replace('px', ''));
		 subPaddingRight = parseInt(subPaddingRight.replace('px', ''));
		 paddingFix = subPaddingLeft + subPaddingRight;
	 }
    if ( jQuery(this).find(".row").length > 0 ) { //If row exists...

        var biggestRow = 0;	
        jQuery(this).find(".row").each(function() {
            jQuery(this).calcSubWidth(); //Call function to calculate width of all ul's
            //Find biggest row
            if(rowWidth > biggestRow) {
                biggestRow = rowWidth;
            }
        });
        jQuery(this).find(".sub").css({width : biggestRow + paddingFix}); //Set width
        jQuery(this).find(".row:last").css({'margin':'0'});  //Kill last row's margin

    } else { //If row does not exist...
        jQuery(this).calcSubWidth();  //Call function to calculate width of all ul's
        jQuery(this).find(".sub").css({'width' : rowWidth + paddingFix}); //Set Width

    }
}
//On Hover Out
function megaHoverOut(){
  jQuery(this).find(".sub").fadeTo(<?php echo $this->getNavConfig('fadeout')?>, 0, function() { //Fade to 0 opactiy
      jQuery(this).hide();  //after fading, hide it
  });
}

//Set custom configurations
var config = {
     sensitivity: <?php echo $this->getNavConfig('sensitivity')?>, // number = sensitivity threshold (must be 1 or higher)
     interval: <?php echo $this->getNavConfig('interval')?>, // number = milliseconds for onMouseOver polling interval
     over: megaHoverOver, // function = onMouseOver callback (REQUIRED)
     timeout: <?php echo $this->getNavConfig('timeout')?>, // number = milliseconds delay before onMouseOut
     out: megaHoverOut // function = onMouseOut callback (REQUIRED)
};
jQuery("ul#pronav li .sub").css({'opacity':'0'}); //Fade sub nav to 0 opacity on default
jQuery("ul#pronav li").hoverIntent(config); //Trigger Hover intent with custom configurations

});
</script>