<script type="text/javascript">
//<![CDATA[
	//var auctionTimeCounters = new Array();
	var dailydealTimeCounters = new Array();
	var i = 0;
//]]>
</script>
<div class="block block-subscribe block-dailydeal">
    <div class="block-title"><strong><span><?php echo $this->__('Daily Deal'); ?></span></strong></div>
        <div class="block-content">
            <?php
                $_productCollection=$this->getSidebarProductCollection();
                $_coreHelper = $this->helper('core');
                $_helper = $this->helper('catalog/output');
            ?>
            <?php if(!$_productCollection->count()): ?>
            <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
            <?php else: ?>
                <div class="category-products">
				<?php $_iterator = 0; ?>
                <?php $count =0; foreach ($_productCollection as $_product): ?>
                <?php $dailydeal=$this->getDailydealByProduct($_product->getEntityId());?>
				<?php if(!$dailydeal->getId()) continue; ?>
                <div class="sidebardailydeal">
                    <div class="item <?php if( ++$_iterator == sizeof($_productCollection) ) echo 'last' ?>">
                        <?php // Product Image
                            if($dailydeal->getThumbnailImage()){
                                $image=Mage::getBaseUrl('media').$dailydeal->getThumbnailImage();
                            }else{
                                $image=$this->helper('catalog/image')->init($_product, 'thumbnail')->resize(210);
                            }
                        ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->getImageLabel($_product, 'small_image') ?>" class="sidebar-product-image">
                            <img src="<?php echo $image;  ?>" alt="<?php echo $this->getImageLabel($_product, 'small_image') ?>" />
                        </a>
                        <?php // Product description ?>
                        <h2 class="dailydeal-sidebar-product-name">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName() ?>"><?php echo $dailydeal->getTitle() ?></a>
                	   </h2>
                	
                    	<ul class="save-sold">
                            <li class="special-price">
                                <?php 
                                    echo $this->__('<label>You save </label>').$_coreHelper->currency($_product->getPrice()-$dailydeal->getDealPrice());
                                ?>
                            </li>
                            <li class="special-price">
                            <?php echo $this->__('<label>Bought </label><span class="price">');?>
                            <?php 
                                    $limit=Mage::getStoreConfig('dailydeal/general/limit');
                                    $items=$dailydeal->getQuantity();
                                    if ($limit>0){
                                        echo $dailydeal->getSold().' '.$this->__('/').$items; 
                                    }else {
                                        echo $dailydeal->getSold().' '.$this->__('/').$items;
                                    }
                                ?>
                        </ul> 
                	
						<ul class="dailydeal-price">                                
							<li class="old-price" ><?php echo $_coreHelper->currency($_product->getPrice()) ?></li>
							<li class="special-price"><?php echo $_coreHelper->currency($dailydeal->getDealPrice()); ?></li>
						</ul>
						
						<?php if($_product->isSaleable()): ?>
						    <?php /*
							<p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-dailydeal" onclick="setLocation('<?php echo Mage::getBlockSingleton('catalog/product_list')->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Buy Now') ?></span></span></button></p>
							*/ ?>
							<a class="btn-dailydeal button" href="<?php echo Mage::getBlockSingleton('catalog/product_list')->getAddToCartUrl($_product) ?>"  title="<?php echo $this->__('Add to Cart') ?>"><?php echo $this->__('Buy Now') ?></a>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
						
						<ul class="time-left"> 
                            <li><label><?php echo $this->__('Time left to buy')?></label></li>
                            <?php $now_time = Mage::getModel('core/date')->timestamp(time()) ?>
                            <?php 
                                    $end_time = Mage::getModel('core/date')->timestamp(strtotime($dailydeal->getCloseTime()));
                             ?>
                            <div class="timeleft" id="timeleft_<?php echo $_product->getId() ?>"> </div>

						</ul>

                        
                    </div>
                </div>
                <script type="text/javascript">
		//<![CDATA[
			dailydealTimeCounters[i] = new DailydealTimeCounter('<?php echo $now_time ?>', '<?php echo $end_time ?>', '<?php echo $dailydeal->getId() ?>');
			dailydealTimeCounters[i].setTimeleft('timeleft_<?php echo $_product->getId() ?>');
		//]]>
		</script>				
                <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
		<script type="text/javascript">decorateGeneric($$('.block-dailydeal .sidebardailydeal'), ['odd','even','first','last'])</script>
</div>